name: Auto-merge Dependabot (minor/patch)
on:
  pull_request:
    types: [opened, edited, synchronize, labeled, unlabeled]
  check_suite:
    types: [completed]
permissions:
  contents: write
  pull-requests: write
jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge
        if: contains(steps.meta.outputs.update-type, 'version-update:semver-minor') || contains(steps.meta.outputs.update-type, 'version-update:semver-patch')
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
